### ISSUE TITLE
Support Grunt not in root folder

### ISSUE THREAD

**Issue by ShawnStrickland** [nickclaw/atom-grunt-runner#15]
Is it possible to support grunt not in the root project folder?  Or is there good supporting evidence that I should have a Gruntfile at the project's root to begin with?

**Comment by BEEware** [comment]
I'll appreciate that function, too. In many projects, the Gruntfile is in the theme folder instead the root folder.

**Comment by xperiments** [comment]
+1

**Comment by thechinnster** [comment]
+1

**Comment by mutschelknauss** [comment]
+1

**Comment by sumobi** [comment]
+1

**Comment by MaevaDbg** [comment]
+1

**Comment by huberd** [comment]
+1

**Comment by smnbbrv** [comment]
Current implementation does not really work for my case. The reason is that my Gruntfile is quite complicated and I have some custom nodejs logic inside, so some of my files are required before the process has switched to it's folder, see parse-config-task.coffee :

```coffeescript
    try
        fn = require(gruntfilePath);
    catch e

    if !fn then return {error: "Gruntfile not found.", path: gruntfilePath}

    # change dir relative to gruntfile so Grunt will load
    # npm packages and other files from correct path
    process.chdir path.dirname gruntfilePath
```

The easiest I've found to fix this issue is the following:

```coffeescript
    try
        # change dir relative to gruntfile so Grunt will load
        # npm packages and other files from correct path
        process.chdir path.dirname gruntfilePath

        fn = require(gruntfilePath);
    catch e

    if !fn then return {error: "Gruntfile not found.", path: gruntfilePath}
```

This works like a charm and I really think this would be a better option for everybody.

**Comment by kokarn** [comment]
This is fixed thanks to @smnbbrv. 
As soon as @nickclaw publishes a new version we should be fine. If you can't wait that long, install the latest version from master.
